export const CREATE_PERSON = 'CREATE_PERSON';
export const UPDATE_PERSON = 'UPDATE_PERSON';
export const LOAD_PERSONS_SUCCESS = 'LOAD_PERSONS_SUCCESS';

export const CREATE_SKILL = 'CREATE_SKILL';
export const UPDATE_SKILL = 'UPDATE_SKILL';
export const LOAD_SKILLS_SUCCESS = 'LOAD_SKILLS_SUCCESS';

export const LOAD_PRESETS_SUCCESS = 'LOAD_PRESETS_SUCCESS';
export const ADD_PRESET = 'ADD_PRESET';

export const ADD_ITEM = 'ADD_ITEM';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const SET_ROOM = 'SET_ROOM';


