export const CREATE_PERSON = 'CREATE_PERSON';
export const UPDATE_PERSON = 'UPDATE_PERSON';
export const LOAD_PERSONS_SUCCESS = 'LOAD_PERSONS_SUCCESS';

export const CREATE_SKILL = 'CREATE_SKILL';
export const UPDATE_SKILL = 'UPDATE_SKILL';
export const LOAD_SKILLS_SUCCESS = 'LOAD_SKILLS_SUCCESS';

